<a href="https://colab.research.google.com/github/JoseColombini/PCS5022-deeplearning/blob/main/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How to
Basics to import files from github

### TODO
- Generalizar para todas as tasks

In [ ]:
import requests
import numpy as np
from io import BytesIO

url = 'https://github.com/JoseColombini/PCS5022-deeplearning/raw/refs/heads/main/dataset1.npz'
response = requests.get(url)

# Check status
if response.status_code == 200:
    data = np.load(BytesIO(response.content))

    # Now you can access arrays inside your .npz file, e.g.:
    print(data.files)  # lists arrays inside the archiveelse:
    print(data['X_train'])
else:
    print("Failed to fetch file:", response.status_code)

['X_train', 'y_train', 'X_val', 'y_val', 'X_test']
[[1.   0.   1.   ... 0.   0.   0.  ]
 [1.   0.   1.   ... 0.   0.   0.  ]
 [1.   0.   1.   ... 0.   0.   0.  ]
 ...
 [0.   0.   0.   ... 2.   2.   7.98]
 [1.   0.   1.   ... 0.   0.   0.  ]
 [0.   0.   0.   ... 1.   1.   4.29]]


# Gerador de CSV para submissão

- use **Y_predict** to save the outputs of your model. It will automatically fit it here to generate the csv

- Be sure you are sending the csv of the correct task

In [ ]:
def run_submission(model, x_test):
    model.eval()
    y_test = []

    # Convert x_test to a torch tensor if it's a numpy array or list
    if isinstance(x_test, (list, np.ndarray)):
        x_test_t = torch.tensor(x_test, dtype=torch.float32)
    else:
        x_test_t = x_test.float()

    for x in x_test_t:
      # Ensure it's 2D: (1, input_size)
      if x.ndim == 1:
          x = x.unsqueeze(0)

      with torch.no_grad():
          output = model(x)
          prob = torch.sigmoid(output).item()
          prediction = 1.0 if prob >= 0.5 else 0.0

          # Append the prediction
          y_test.append(prediction)

    return y_test

y_test = run_submission(model, X_test)
print(y_test)

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0,

In [ ]:
import numpy as np
import pandas as pd

# Carrega a base de dados a partir de seu caminho
# data = np.load(dataset)
# X_test = data['X_test']

# Faz palpites aleatórios
num_samples = X_test.shape[0]
# random_predictions = np.random.randint(0, 2, size=num_samples)

# Gera um DataFrame no formato esperado da submissão
submission_df = pd.DataFrame({
    'ID': np.arange(1, num_samples + 1),
    'Prediction': y_test
})

# Salva o arquivo CSV no diretório atual
submission_df.to_csv('submission.csv', index=False)

# Task 1

### TODO
- Dividir em varios blocos menores e talvez reutilizar para outras tasks
- Fazer um modelo de verdade
- refatorar

In [ ]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision.transforms import ToTensor
from torch.utils.data import TensorDataset, DataLoader
import torch.nn as nn
import torch.optim as optim

device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"
print(f"Using {device} device")

X_train = data['X_train']
Y_train = data['y_train']
print(X_train.shape[1])
print(Y_train)


print(data)

class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(119, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 32),
            nn.ReLU(),
            nn.Linear(32, 16),
            nn.ReLU(),
            nn.Linear(16, 8),
            nn.ReLU(),
            nn.Linear(8, 4),
            nn.ReLU(),
            nn.Linear(4, 2),
            nn.ReLU(),
            nn.Linear(2, 1),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits


# Convert numpy arrays to torch tensors
X_train_t = torch.tensor(X_train, dtype=torch.float32)
Y_train_t = torch.tensor(Y_train, dtype=torch.float32)  # float for BCEWithLogitsLoss

# Dataset and DataLoader
train_dataset = TensorDataset(X_train_t, Y_train_t)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

# Instantiate model
model = NeuralNetwork()

# Use BCEWithLogitsLoss for binary classification
loss_fn = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters(), lr=1e-3)

num_epochs = 10

for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0

    for batch_X, batch_Y in train_loader:
        optimizer.zero_grad()
        outputs = model(batch_X).squeeze()  # (batch_size,) shape

        loss = loss_fn(outputs, batch_Y)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * batch_X.size(0)

    epoch_loss = running_loss / len(train_dataset)
    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {epoch_loss:.4f}")




Using cuda device
119
[1 1 1 ... 0 1 1]
NpzFile 'object' with keys: X_train, y_train, X_val, y_val, X_test
Epoch 1/10, Loss: 0.5539
Epoch 2/10, Loss: 0.5383
Epoch 3/10, Loss: 0.5236
Epoch 4/10, Loss: 0.5253
Epoch 5/10, Loss: 0.5159
Epoch 6/10, Loss: 0.5131
Epoch 7/10, Loss: 0.5109
Epoch 8/10, Loss: 0.5091
Epoch 9/10, Loss: 0.5073
Epoch 10/10, Loss: 0.5062


In [ ]:
x_val = data['X_val']
y_val = data['y_val']
X_val_t = torch.tensor(x_val, dtype=torch.float32)
y_val_t = torch.tensor(y_val, dtype=torch.float32)

def evaluate(model, X, y, batch_size=32):
    model.eval()
    val_dataset = torch.utils.data.TensorDataset(X, y)
    val_loader = torch.utils.data.DataLoader(val_dataset, batch_size=batch_size)

    loss_fn = nn.BCEWithLogitsLoss()
    total_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():
        for batch_X, batch_y in val_loader:
            outputs = model(batch_X).squeeze()
            loss = loss_fn(outputs, batch_y)
            total_loss += loss.item() * batch_X.size(0)

            # Get predicted labels: sigmoid + threshold at 0.5
            probs = torch.sigmoid(outputs)
            preds = (probs >= 0.5).float()
            correct += (preds == batch_y).sum().item()
            total += batch_X.size(0)

    avg_loss = total_loss / total
    accuracy = correct / total
    return avg_loss, accuracy

val_loss, val_accuracy = evaluate(model, X_val_t, y_val_t)
print(f"Validation Loss: {val_loss:.4f}, Accuracy: {val_accuracy:.2%}")

Validation Loss: 0.7165, Accuracy: 64.52%


In [ ]:
X_test = data['X_test']

# Paper

In [2]:
from sklearn.datasets import make_classification
import torch
from torch.utils.data import DataLoader, TensorDataset
import torch.nn as nn
import torch.optim as optim

gerar dados sintéticos

In [75]:
N = 50000
# Generate synthetic data/
X_synthetic, y_synthetic = make_classification(n_samples=N, n_features=20, n_informative=4,n_classes=4, random_state=42)

# X contains the features, y contains the labels
print(X_synthetic.shape, y_synthetic.shape)

x_train = X_synthetic[:round(0.8*N)]
y_train = y_synthetic[:round(0.8*N)]
x_eval = X_synthetic[round(0.8*N):N]
y_eval = y_synthetic[round(0.8*N):N]

y_train_0 = [1 if y == 0 else 0 for y in y_train]
y_train_1 = [1 if y == 1 else 0 for y in y_train]
y_train_2 = [1 if y == 2 else 0 for y in y_train]

y_eval_0 = [1 if y == 0 else 0 for y in y_eval]
y_eval_1 = [1 if y == 1 else 0 for y in y_eval]
y_eval_2 = [1 if y == 2 else 0 for y in y_eval]


y_train_t = []
y_eval_t = []
train_dataset = []
train_loader = []

x_train_t = torch.tensor(x_train, dtype=torch.float32)
y_train_t.append(torch.tensor(y_train_0, dtype=torch.float32))  # float for BCEWithLogitsLoss
y_train_t.append(torch.tensor(y_train_1, dtype=torch.float32))  # float for BCEWithLogitsLoss
y_train_t.append(torch.tensor(y_train_2, dtype=torch.float32))  # float for BCEWithLogitsLoss


x_eval_t = torch.tensor(x_eval, dtype=torch.float32)
y_eval_t.append(torch.tensor(y_eval_0, dtype=torch.float32))  # float for BCEWithLogitsLoss
y_eval_t.append(torch.tensor(y_eval_1, dtype=torch.float32))  # float for BCEWithLogitsLoss
y_eval_t.append(torch.tensor(y_eval_2, dtype=torch.float32))  # float for BCEWithLogitsLoss


# Dataset and DataLoader
train_dataset.append(TensorDataset(x_train_t, y_train_t[0]))
train_loader.append(DataLoader(train_dataset[0], batch_size=64, shuffle=True))

train_dataset.append(TensorDataset(x_train_t, y_train_t[1]))
train_loader.append(DataLoader(train_dataset[1], batch_size=64, shuffle=True))

train_dataset.append(TensorDataset(x_train_t, y_train_t[2]))
train_loader.append(DataLoader(train_dataset[2], batch_size=64, shuffle=True))

print(y_synthetic)


(50000, 20) (50000,)
[3 0 0 ... 0 0 3]


Nerual netwok

In [76]:

class SimpleDeepWideNN(nn.Module):
    def __init__(self):
        super(SimpleDeepWideNN, self).__init__()
        self.layers = nn.Sequential(
            nn.Linear(20, 128),  # Wide layer
            nn.ReLU(),
            nn.BatchNorm1d(128),
            nn.Dropout(0.5),

            nn.Linear(128, 256),  # Wider layer
            nn.ReLU(),
            nn.BatchNorm1d(256),
            nn.Dropout(0.5),

            nn.Linear(256, 128),  # Start reducing width
            nn.ReLU(),
            nn.BatchNorm1d(128),

            nn.Linear(128, 64),  # Further reduce width
            nn.ReLU(),
            nn.BatchNorm1d(64),

            nn.Linear(64, 32),  # Narrow layer
            nn.ReLU(),

            nn.Linear(32, 1)  # Output layer for 2 classes
        )

    def forward(self, x):
        return self.layers(x)

model = [SimpleDeepWideNN(), SimpleDeepWideNN(), SimpleDeepWideNN()]
# Example of creating the model


Training

In [77]:
loss_fn = nn.BCEWithLogitsLoss()

num_epochs = 25

#Create the base network
optimizer = optim.Adam(model[0].parameters(), lr=1e-3)
for epoch in range(num_epochs):
    model[0].train()
    running_loss = 0.0

    for batch_X, batch_Y in train_loader[0]:
        optimizer.zero_grad()
        outputs = model[0](batch_X).squeeze()  # (batch_size,) shape
        loss = loss_fn(outputs, batch_Y)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * batch_X.size(0)

    epoch_loss = running_loss / len(train_dataset[0])
    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {epoch_loss:.4f}")

#both are copies of the base one
for p0, p1, p2 in zip(model[0].parameters(), model[1].parameters(), model[2].parameters()):
  for i in range(len(p1)):
    p1[i].data.copy_(p0[i])
    p2[i].data.copy_(p0[i])

#They are finetuned for another task
for i in range(1, len(model)):
  optimizer = optim.Adam(model[i].parameters(), lr=1e-3)
  for epoch in range(num_epochs):
      model[i].train()
      running_loss = 0.0

      for batch_X, batch_Y in train_loader[i]:
          optimizer.zero_grad()
          outputs = model[i](batch_X).squeeze()  # (batch_size,) shape
          loss = loss_fn(outputs, batch_Y)
          loss.backward()
          optimizer.step()

          running_loss += loss.item() * batch_X.size(0)

      epoch_loss = running_loss / len(train_dataset[i])
      print(f"Epoch {epoch+1}/{num_epochs}, Loss: {epoch_loss:.4f}")


Epoch 1/25, Loss: 0.3935
Epoch 2/25, Loss: 0.3006
Epoch 3/25, Loss: 0.2711
Epoch 4/25, Loss: 0.2608
Epoch 5/25, Loss: 0.2495
Epoch 6/25, Loss: 0.2492
Epoch 7/25, Loss: 0.2425
Epoch 8/25, Loss: 0.2383
Epoch 9/25, Loss: 0.2371
Epoch 10/25, Loss: 0.2328
Epoch 11/25, Loss: 0.2285
Epoch 12/25, Loss: 0.2263
Epoch 13/25, Loss: 0.2249
Epoch 14/25, Loss: 0.2238
Epoch 15/25, Loss: 0.2208
Epoch 16/25, Loss: 0.2200
Epoch 17/25, Loss: 0.2172
Epoch 18/25, Loss: 0.2178
Epoch 19/25, Loss: 0.2165
Epoch 20/25, Loss: 0.2171
Epoch 21/25, Loss: 0.2149
Epoch 22/25, Loss: 0.2131
Epoch 23/25, Loss: 0.2135
Epoch 24/25, Loss: 0.2106
Epoch 25/25, Loss: 0.2107
Epoch 1/25, Loss: 0.3184
Epoch 2/25, Loss: 0.2502
Epoch 3/25, Loss: 0.2384
Epoch 4/25, Loss: 0.2326
Epoch 5/25, Loss: 0.2258
Epoch 6/25, Loss: 0.2262
Epoch 7/25, Loss: 0.2220
Epoch 8/25, Loss: 0.2200
Epoch 9/25, Loss: 0.2139
Epoch 10/25, Loss: 0.2137
Epoch 11/25, Loss: 0.2116
Epoch 12/25, Loss: 0.2114
Epoch 13/25, Loss: 0.2101
Epoch 14/25, Loss: 0.2084
Epoc

model eval

In [78]:
def evaluate(model, X, y, batch_size=32):
    model.eval()
    val_dataset = torch.utils.data.TensorDataset(X, y)
    val_loader = torch.utils.data.DataLoader(val_dataset, batch_size=batch_size)

    loss_fn = nn.BCEWithLogitsLoss()
    total_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():
        for batch_X, batch_y in val_loader:
            outputs = model(batch_X).squeeze()
            loss = loss_fn(outputs, batch_y)
            total_loss += loss.item() * batch_X.size(0)

            # Get predicted labels: sigmoid + threshold at 0.5
            probs = torch.sigmoid(outputs)
            preds = (probs >= 0.5).float()
            correct += (preds == batch_y).sum().item()
            total += batch_X.size(0)

    avg_loss = total_loss / total
    accuracy = correct / total
    return avg_loss, accuracy

for i in range(3):
  for j in range(3):
    val_loss, val_accuracy = evaluate(model[i], x_eval_t, y_eval_t[j])
    print(f"Validation for model {i} with data {j} Loss: {val_loss:.4f}, Accuracy: {val_accuracy:.2%}")


Validation for model 0 with data 0 Loss: 0.1804, Accuracy: 92.54%
Validation for model 0 with data 1 Loss: 1.6439, Accuracy: 53.65%
Validation for model 0 with data 2 Loss: 1.7837, Accuracy: 53.84%
Validation for model 1 with data 0 Loss: 1.8099, Accuracy: 54.58%
Validation for model 1 with data 1 Loss: 0.1791, Accuracy: 92.73%
Validation for model 1 with data 2 Loss: 1.8942, Accuracy: 53.24%
Validation for model 2 with data 0 Loss: 1.9513, Accuracy: 51.51%
Validation for model 2 with data 1 Loss: 2.1207, Accuracy: 51.88%
Validation for model 2 with data 2 Loss: 0.1298, Accuracy: 94.87%


getting model pts

In [79]:
class Merged_SimpleDeepWideNN(nn.Module):
    def __init__(self):
        super(Merged_SimpleDeepWideNN, self).__init__()
        self.layers = nn.Sequential(
            nn.Linear(20, 128),  # Wide layer
            nn.ReLU(),
            nn.BatchNorm1d(128),
            nn.Dropout(0.5),

            nn.Linear(128, 256),  # Wider layer
            nn.ReLU(),
            nn.BatchNorm1d(256),
            nn.Dropout(0.5),

            nn.Linear(256, 128),  # Start reducing width
            nn.ReLU(),
            nn.BatchNorm1d(128),

            nn.Linear(128, 64),  # Further reduce width
            nn.ReLU(),
            nn.BatchNorm1d(64),

            nn.Linear(64, 32),  # Narrow layer
            nn.ReLU(),

            nn.Linear(32, 2)  # Output layer for 2 classes
        )

    def forward(self, x):
        return self.layers(x)

In [80]:
# for param in model[1].parameters():
#   print(param)

print(type(model[0].parameters()))

merger  = Merged_SimpleDeepWideNN()

for p0, p1, p2, pm, layer in zip(model[0].parameters(), model[1].parameters(), model[2].parameters(), merger.parameters(), range(30)):

  # print(p0.shape)
  # print(layer)
  if layer < 18:
    for i in range(len(p1)):
      a = (p1[i] - p0[i]) + (p2[i] - p0[i]) + p0[0]
      pm[i].data.copy_(a)
      # print(pm[i])
  else:
    pm[0].data.copy_(p1[0])
    pm[1].data.copy_(p2[0])


# torch.save(merger.state_dict(), 'mmerger_parameters.pth')




<class 'generator'>


In [81]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def evaluate_merged(model, X, y, batch_size=32):
    """
    Evaluate the performance of the model on the given data.

    Args:
    - model: The neural network model to evaluate.
    - X: Input features.
    - y: True labels.
    - batch_size: Batch size for the DataLoader.

    Returns:
    - A dictionary containing average loss and accuracy.
    """
    model.eval()  # Set the model to evaluation mode
    val_dataset = torch.utils.data.TensorDataset(X, y)
    val_loader = torch.utils.data.DataLoader(val_dataset, batch_size=batch_size)
    loss_fn = nn.CrossEntropyLoss()  # Use CrossEntropyLoss for multi-class classification
    total_loss = 0.0
    correct = 0
    total = 0
    all_labels = []
    all_predictions = []

    with torch.no_grad():  # Disable gradient computation
        for batch_X, batch_y in val_loader:
            outputs = model(batch_X)
            # loss = loss_fn(outputs, batch_y)
            # total_loss += loss.item() * batch_X.size(0)
            probs = torch.sigmoid(outputs)
            # preds = (probs >= 0.5).float()
            _, predicted = torch.max(probs, 1)  # Get the predicted class
            _, label_pred = torch.max(probs, 1)
            # print(probs)
            # print(predicted)
            # print(predicted[0])
            # print(probs[predicted[0]])
            for probability, index, pred_index in zip(probs, predicted, range(len(label_pred))):
              if probability[index] >= 0.5:
                label_pred[pred_index] = float(index + 1)
              else:
                label_pred[pred_index] = float(0)

            all_labels.extend(batch_y.cpu().numpy())
            all_predictions.extend(label_pred.cpu().numpy())

    # Calculate metrics
    # avg_loss = total_loss / len(val_loader.dataset)
    accuracy = accuracy_score(all_labels, all_predictions)
    # precision = precision_score(all_labels, all_predictions)
    # recall = recall_score(all_labels, all_predictions)
    # f1 = f1_score(all_labels, all_predictions)
    print(all_labels)
    print(all_predictions)

    return 0, accuracy

y_eval_merged = [1 if y == 1 else 2 if y == 2 else 0 for y in y_eval]
y_eval_merged_t = torch.tensor(y_eval_merged, dtype=torch.float32)  # float for BCEWithLogitsLoss

val_loss, val_accuracy = evaluate_merged(merger, x_eval_t, y_eval_merged_t)
print(f"Validation for model merged with Loss: {val_loss:.4f}, Accuracy: {val_accuracy:.2%}")

# val_loss, val_accuracy = evaluate_merged(merger, x_eval_t, y_eval_t[2])
# print(f"Validation for model merged with Loss: {val_loss:.4f}, Accuracy: {val_accuracy:.2%}")


[np.float32(1.0), np.float32(0.0), np.float32(0.0), np.float32(1.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(1.0), np.float32(1.0), np.float32(0.0), np.float32(2.0), np.float32(1.0), np.float32(1.0), np.float32(0.0), np.float32(0.0), np.float32(1.0), np.float32(0.0), np.float32(1.0), np.float32(2.0), np.float32(1.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(1.0), np.float32(0.0), np.float32(2.0), np.float32(2.0), np.float32(0.0), np.float32(1.0), np.float32(1.0), np.float32(1.0), np.float32(1.0), np.float32(1.0), np.float32(0.0), np.float32(1.0), np.float32(0.0), np.float32(2.0), np.float32(1.0), np.float32(2.0), np.float32(0.0), np.float32(1.0), np.float32(0.0), np.float32(0.0), np.float32(1.0), np.float32(2.0), np.float32(1.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(2.0), np.float32(0.0), np.float32(0.0), np.float32(1.0), np.float32(0.0), np.float32(1.0), np.float32(2.0), np.float32(1.0), np.float32(1.0), np.float32(2.