<a href="https://colab.research.google.com/github/JoseColombini/PCS5022-deeplearning/blob/main/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How to
Basics to import files from github

### TODO
- Generalizar para todas as tasks

In [ ]:
import requests
import numpy as np
from io import BytesIO

url = 'https://github.com/JoseColombini/PCS5022-deeplearning/raw/refs/heads/main/dataset1.npz'
response = requests.get(url)

# Check status
if response.status_code == 200:
    data = np.load(BytesIO(response.content))

    # Now you can access arrays inside your .npz file, e.g.:
    print(data.files)  # lists arrays inside the archiveelse:
    print(data['X_train'])
else:
    print("Failed to fetch file:", response.status_code)

['X_train', 'y_train', 'X_val', 'y_val', 'X_test']
[[1.   0.   1.   ... 0.   0.   0.  ]
 [1.   0.   1.   ... 0.   0.   0.  ]
 [1.   0.   1.   ... 0.   0.   0.  ]
 ...
 [0.   0.   0.   ... 2.   2.   7.98]
 [1.   0.   1.   ... 0.   0.   0.  ]
 [0.   0.   0.   ... 1.   1.   4.29]]


# Gerador de CSV para submissão

- use **Y_predict** to save the outputs of your model. It will automatically fit it here to generate the csv

- Be sure you are sending the csv of the correct task

In [ ]:
def run_submission(model, x_test):
    model.eval()
    y_test = []

    # Convert x_test to a torch tensor if it's a numpy array or list
    if isinstance(x_test, (list, np.ndarray)):
        x_test_t = torch.tensor(x_test, dtype=torch.float32)
    else:
        x_test_t = x_test.float()

    for x in x_test_t:
      # Ensure it's 2D: (1, input_size)
      if x.ndim == 1:
          x = x.unsqueeze(0)

      with torch.no_grad():
          output = model(x)
          prob = torch.sigmoid(output).item()
          prediction = 1.0 if prob >= 0.5 else 0.0

          # Append the prediction
          y_test.append(prediction)

    return y_test

y_test = run_submission(model, X_test)
print(y_test)

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0,

In [ ]:
import numpy as np
import pandas as pd

# Carrega a base de dados a partir de seu caminho
# data = np.load(dataset)
# X_test = data['X_test']

# Faz palpites aleatórios
num_samples = X_test.shape[0]
# random_predictions = np.random.randint(0, 2, size=num_samples)

# Gera um DataFrame no formato esperado da submissão
submission_df = pd.DataFrame({
    'ID': np.arange(1, num_samples + 1),
    'Prediction': y_test
})

# Salva o arquivo CSV no diretório atual
submission_df.to_csv('submission.csv', index=False)

# Task 1

### TODO
- Dividir em varios blocos menores e talvez reutilizar para outras tasks
- Fazer um modelo de verdade
- refatorar

In [ ]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision.transforms import ToTensor
from torch.utils.data import TensorDataset, DataLoader
import torch.nn as nn
import torch.optim as optim

device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"
print(f"Using {device} device")

X_train = data['X_train']
Y_train = data['y_train']
print(X_train.shape[1])
print(Y_train)


print(data)

class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(119, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 32),
            nn.ReLU(),
            nn.Linear(32, 16),
            nn.ReLU(),
            nn.Linear(16, 8),
            nn.ReLU(),
            nn.Linear(8, 4),
            nn.ReLU(),
            nn.Linear(4, 2),
            nn.ReLU(),
            nn.Linear(2, 1),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits


# Convert numpy arrays to torch tensors
X_train_t = torch.tensor(X_train, dtype=torch.float32)
Y_train_t = torch.tensor(Y_train, dtype=torch.float32)  # float for BCEWithLogitsLoss

# Dataset and DataLoader
train_dataset = TensorDataset(X_train_t, Y_train_t)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

# Instantiate model
model = NeuralNetwork()

# Use BCEWithLogitsLoss for binary classification
loss_fn = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters(), lr=1e-3)

num_epochs = 10

for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0

    for batch_X, batch_Y in train_loader:
        optimizer.zero_grad()
        outputs = model(batch_X).squeeze()  # (batch_size,) shape

        loss = loss_fn(outputs, batch_Y)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * batch_X.size(0)

    epoch_loss = running_loss / len(train_dataset)
    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {epoch_loss:.4f}")




Using cuda device
119
[1 1 1 ... 0 1 1]
NpzFile 'object' with keys: X_train, y_train, X_val, y_val, X_test
Epoch 1/10, Loss: 0.5539
Epoch 2/10, Loss: 0.5383
Epoch 3/10, Loss: 0.5236
Epoch 4/10, Loss: 0.5253
Epoch 5/10, Loss: 0.5159
Epoch 6/10, Loss: 0.5131
Epoch 7/10, Loss: 0.5109
Epoch 8/10, Loss: 0.5091
Epoch 9/10, Loss: 0.5073
Epoch 10/10, Loss: 0.5062


In [ ]:
x_val = data['X_val']
y_val = data['y_val']
X_val_t = torch.tensor(x_val, dtype=torch.float32)
y_val_t = torch.tensor(y_val, dtype=torch.float32)

def evaluate(model, X, y, batch_size=32):
    model.eval()
    val_dataset = torch.utils.data.TensorDataset(X, y)
    val_loader = torch.utils.data.DataLoader(val_dataset, batch_size=batch_size)

    loss_fn = nn.BCEWithLogitsLoss()
    total_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():
        for batch_X, batch_y in val_loader:
            outputs = model(batch_X).squeeze()
            loss = loss_fn(outputs, batch_y)
            total_loss += loss.item() * batch_X.size(0)

            # Get predicted labels: sigmoid + threshold at 0.5
            probs = torch.sigmoid(outputs)
            preds = (probs >= 0.5).float()
            correct += (preds == batch_y).sum().item()
            total += batch_X.size(0)

    avg_loss = total_loss / total
    accuracy = correct / total
    return avg_loss, accuracy

val_loss, val_accuracy = evaluate(model, X_val_t, y_val_t)
print(f"Validation Loss: {val_loss:.4f}, Accuracy: {val_accuracy:.2%}")

Validation Loss: 0.7165, Accuracy: 64.52%


In [ ]:
X_test = data['X_test']

# Paper

In [2]:
from sklearn.datasets import make_classification
import torch
from torch.utils.data import DataLoader, TensorDataset
import torch.nn as nn
import torch.optim as optim

gerar dados sintéticos

In [72]:

# Generate synthetic data
X_synthetic, y_synthetic = make_classification(n_samples=40000, n_features=20, n_informative=10,n_classes=4, random_state=42)

# X contains the features, y contains the labels
print(X_synthetic.shape, y_synthetic.shape)

x_train = X_synthetic[:32000]
y_train = y_synthetic[:32000]
x_eval = X_synthetic[32000:40000]
y_eval = y_synthetic[32000:40000]

y_train_0 = [1 if y == 0 else 0 for y in y_train]
y_train_1 = [1 if y == 1 else 0 for y in y_train]
y_train_2 = [1 if y == 2 else 0 for y in y_train]

y_eval_0 = [1 if y == 0 else 0 for y in y_eval]
y_eval_1 = [1 if y == 1 else 0 for y in y_eval]
y_eval_2 = [1 if y == 2 else 0 for y in y_eval]


y_train_t = []
y_eval_t = []
train_dataset = []
train_loader = []

x_train_t = torch.tensor(x_train, dtype=torch.float32)
y_train_t.append(torch.tensor(y_train_0, dtype=torch.float32))  # float for BCEWithLogitsLoss
y_train_t.append(torch.tensor(y_train_1, dtype=torch.float32))  # float for BCEWithLogitsLoss


x_eval_t = torch.tensor(x_eval, dtype=torch.float32)
y_eval_t.append(torch.tensor(y_eval_0, dtype=torch.float32))  # float for BCEWithLogitsLoss
y_eval_t.append(torch.tensor(y_eval_1, dtype=torch.float32))  # float for BCEWithLogitsLoss

# Dataset and DataLoader
train_dataset.append(TensorDataset(x_train_t, y_train_t[0]))
train_loader.append(DataLoader(train_dataset[0], batch_size=64, shuffle=True))

train_dataset.append(TensorDataset(x_train_t, y_train_t[1]))
train_loader.append(DataLoader(train_dataset[1], batch_size=64, shuffle=True))

print(y_synthetic)


(40000, 20) (40000,)
[3 0 2 ... 2 0 3]


Nerual netwok

In [73]:

class SimpleDeepWideNN(nn.Module):
    def __init__(self):
        super(SimpleDeepWideNN, self).__init__()
        self.layers = nn.Sequential(
            nn.Linear(20, 128),  # Wide layer
            nn.ReLU(),
            nn.BatchNorm1d(128),
            nn.Dropout(0.5),

            nn.Linear(128, 256),  # Wider layer
            nn.ReLU(),
            nn.BatchNorm1d(256),
            nn.Dropout(0.5),

            nn.Linear(256, 128),  # Start reducing width
            nn.ReLU(),
            nn.BatchNorm1d(128),

            nn.Linear(128, 64),  # Further reduce width
            nn.ReLU(),
            nn.BatchNorm1d(64),

            nn.Linear(64, 32),  # Narrow layer
            nn.ReLU(),

            nn.Linear(32, 1)  # Output layer for 2 classes
        )

    def forward(self, x):
        return self.layers(x)

model = [SimpleDeepWideNN(), SimpleDeepWideNN()]
# Example of creating the model


Training

In [74]:
loss_fn = nn.BCEWithLogitsLoss()

num_epochs = 10


for i in range(len(model)):
  optimizer = optim.Adam(model[i].parameters(), lr=1e-3)
  for epoch in range(num_epochs):
      model[i].train()
      running_loss = 0.0

      for batch_X, batch_Y in train_loader[i]:
          optimizer.zero_grad()
          outputs = model[i](batch_X).squeeze()  # (batch_size,) shape
          loss = loss_fn(outputs, batch_Y)
          loss.backward()
          optimizer.step()

          running_loss += loss.item() * batch_X.size(0)

      epoch_loss = running_loss / len(train_dataset[i])
      print(f"Epoch {epoch+1}/{num_epochs}, Loss: {epoch_loss:.4f}")


Epoch 1/10, Loss: 0.3090
Epoch 2/10, Loss: 0.2246
Epoch 3/10, Loss: 0.1948
Epoch 4/10, Loss: 0.1785
Epoch 5/10, Loss: 0.1594
Epoch 6/10, Loss: 0.1533
Epoch 7/10, Loss: 0.1407
Epoch 8/10, Loss: 0.1353
Epoch 9/10, Loss: 0.1298
Epoch 10/10, Loss: 0.1222
Epoch 1/10, Loss: 0.3397
Epoch 2/10, Loss: 0.2595
Epoch 3/10, Loss: 0.2340
Epoch 4/10, Loss: 0.2122
Epoch 5/10, Loss: 0.2007
Epoch 6/10, Loss: 0.1889
Epoch 7/10, Loss: 0.1843
Epoch 8/10, Loss: 0.1748
Epoch 9/10, Loss: 0.1727
Epoch 10/10, Loss: 0.1699


model eval

In [76]:
def evaluate(model, X, y, batch_size=32):
    model.eval()
    val_dataset = torch.utils.data.TensorDataset(X, y)
    val_loader = torch.utils.data.DataLoader(val_dataset, batch_size=batch_size)

    loss_fn = nn.BCEWithLogitsLoss()
    total_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():
        for batch_X, batch_y in val_loader:
            outputs = model(batch_X).squeeze()
            loss = loss_fn(outputs, batch_y)
            total_loss += loss.item() * batch_X.size(0)

            # Get predicted labels: sigmoid + threshold at 0.5
            probs = torch.sigmoid(outputs)
            preds = (probs >= 0.5).float()
            correct += (preds == batch_y).sum().item()
            total += batch_X.size(0)

    avg_loss = total_loss / total
    accuracy = correct / total
    return avg_loss, accuracy

val_loss, val_accuracy = evaluate(model[0], x_eval_t, y_eval_t[0])
print(f"Validation Loss: {val_loss:.4f}, Accuracy: {val_accuracy:.2%}")

val_loss, val_accuracy = evaluate(model[1], x_eval_t, y_eval_t[1])
print(f"Validation Loss: {val_loss:.4f}, Accuracy: {val_accuracy:.2%}")

Validation Loss: 0.0768, Accuracy: 97.58%
Validation Loss: 0.1219, Accuracy: 95.33%


getting model pts

In [100]:
# for param in model[1].parameters():
#   print(param)

print(type(model[0].parameters()))

merger  = SimpleDeepWideNN()

for p1, p2, p3 in zip(model[0].parameters(), model[1].parameters(), merger.parameters()):
  for i in range(len(p1)):
    print(p1[i])
    print(p2[i])
    a = p1[i] + p2[i]
    p3[i].data.copy_(a)
    print(p3[i])


Streaming output truncated to the last 5000 lines.
        -0.1379,  0.0322,  0.0135, -0.0761,  0.0158,  0.1188,  0.0607,  0.0292,
        -0.1715,  0.0515,  0.0316, -0.0849, -0.0437, -0.0318, -0.0904, -0.0872,
        -0.0045,  0.0857,  0.0319,  0.0459, -0.1050, -0.1977, -0.0152, -0.1607,
         0.0759,  0.0362, -0.0558, -0.0500, -0.1147, -0.1470, -0.1241, -0.0553,
        -0.0896, -0.0572, -0.0468,  0.0962, -0.1532, -0.0554, -0.1268,  0.0015],
       grad_fn=<SelectBackward0>)
tensor([-0.0477, -0.0622, -0.1521, -0.1084, -0.0093, -0.1581, -0.1945, -0.1985,
        -0.1013,  0.0198, -0.1702, -0.2055,  0.0697, -0.0750,  0.0313,  0.2399,
        -0.2207, -0.0830, -0.0556,  0.1693,  0.0100, -0.0863, -0.3601, -0.0242,
        -0.2012,  0.0687, -0.0895,  0.0034, -0.1413, -0.1589,  0.0366,  0.2191,
        -0.0311,  0.1195, -0.0060,  0.1529,  0.0086,  0.0472, -0.0871,  0.1480,
        -0.1356,  0.1206,  0.0575,  0.2196,  0.0255,  0.1289, -0.2059,  0.2163,
        -0.0789, -0.0244,  0.1620,